### PR TITLE
Updated EpicSpawnersHook

### PR DESCRIPTION
**Pull request by SirBlobman**
- Changed to API version 5.2
- Fixed minor compilation issues due to bukkit version names

### CODE REVIEW

**Comment by SirBlobman** [comment]
@Phoenix616 
Will do 👍

**Comment by SirBlobman** [comment]
Apparently EpicSpawners doesn't have a public repo with `EpicSpawners-API` so I'll just update the module with the proper classes

**Comment by Phoenix616** [comment]
Please don't include the full code of the API, just the classes and methods that are required to make it work and make them throw UnsupportedOperationExceptions like before. That makes it easier to organise this and avoids potential licensing issues with included code.

Also it might be worth adding the original API version that the module is based on to the artifact version, that way we have that information easily accessible in the future.

**Comment by SirBlobman** [comment]
Should be done now 👍

**Comment by novucs** [comment]
I've just tested this with the latest EpicSpawners, it seems `SpawnerChangeEvent` is never called by EpicSpawners.

**Comment by SirBlobman** [comment]
I tried to keep it as close to the original as possible, and I don't know the alternative so I'll just let you do the rest. Someone just requested an update and I figured I would submit a PR to the original.

**Comment by novucs** [comment]
Ah no worries! It's just me being overly picky to keep our codebase as small as possible. You've done a good job, thanks for your help. :+1:

**Comment by SirBlobman** [comment]
No problem 😺

**Comment by MedicOP** [comment]
Check my pull request for working version
https://github.com/novucs/factions-top/pull/104

**Pull request closed without merging**
